version: '3'

services:
  node:
    restart: always
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    build:
      context: .
      target: development
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - my-network
  mongo:
    image: mongo
    restart: always
    volumes:
      - ../mongosackdaten/:/data/db
    networks:
      - my-network
networks:
  my-network:
